package postgres

import (
	"slices"
	"strings"
	"testing"

	"github.com/ikigai-db/ikigai-db/internal/model"
	"github.com/ikigai-db/ikigai-db/internal/source"
)

func col(name, native string, nullable bool) model.Column {
	return model.Column{Name: name, Type: model.DataType{
		Class: model.TypeString, Native: native, Nullable: nullable, Length: -1}}
}

// people is the table these render against.
func people() *model.Table {
	return &model.Table{
		Name: "people",
		Columns: []model.Column{
			{Name: "id", Type: model.DataType{Class: model.TypeInteger, Native: "integer"}, Identity: true},
			col("name", "text", false),
			col("note", "varchar(40)", true),
		},
		PrimaryKey: &model.PrimaryKey{Name: "people_pkey", Columns: []string{"id"}},
	}
}

func sqlOf(t *testing.T, stmts []source.Statement, err error) []string {
	t.Helper()
	if err != nil {
		t.Fatalf("rendering: %v", err)
	}
	out := make([]string, len(stmts))
	for i, s := range stmts {
		out[i] = s.SQL
	}
	return out
}

// altered, created and dropped render one change, so that a test reads as
// what it is asking rather than as two lines of plumbing.
// peopleRef names the fixture table the way the explorer does.
var peopleRef = model.NewRef(model.KindTable, "db", "public", "people")

func altered(t *testing.T, from, to *model.Table) []string {
	t.Helper()
	stmts, err := dialect{}.AlterObject(peopleRef, from, to)
	return sqlOf(t, stmts, err)
}

func created(t *testing.T, tbl *model.Table) []string {
	t.Helper()
	stmts, err := dialect{}.CreateObject(peopleRef, tbl)
	return sqlOf(t, stmts, err)
}

// createdObj renders any object, which is how the source kinds are asked.
func createdObj(t *testing.T, ref model.ObjectRef, obj any) []string {
	t.Helper()
	stmts, err := dialect{}.CreateObject(ref, obj)
	return sqlOf(t, stmts, err)
}

func renamedSQL(t *testing.T, ref model.ObjectRef, from, to string) []string {
	t.Helper()
	stmts, err := dialect{}.RenameColumn(ref, from, to)
	return sqlOf(t, stmts, err)
}

func droppedSQL(t *testing.T, ref model.ObjectRef, cascade bool) []string {
	t.Helper()
	stmts, err := dialect{}.DropObject(ref, cascade)
	return sqlOf(t, stmts, err)
}

func TestATableRenderedWhole(t *testing.T) {
	tbl := people()
	tbl.Comment = "who they are"
	tbl.Columns[1].Comment = "what they are called"
	tbl.Uniques = []model.UniqueConstraint{{Name: "people_name_key", Columns: []string{"name"}}}
	tbl.Checks = []model.CheckConstraint{{Name: "people_name_len", Expression: "length(name) > 0"}}
	tbl.ForeignKeys = []model.ForeignKey{{Name: "people_note_fk", Columns: []string{"note"},
		RefSchema: "public", RefTable: "notes", RefColumns: []string{"id"}, OnDelete: model.ActionCascade}}
	tbl.Indexes = []model.Index{{Name: "people_note_idx", Method: "btree",
		Columns: []model.IndexColumn{{Name: "note", Descending: true}}}}

	got := created(t, tbl)
	if len(got) != 4 {
		t.Fatalf("it rendered %d statements:\n%s", len(got), strings.Join(got, "\n"))
	}
	create := got[0]
	for _, want := range []string{
		`CREATE TABLE "public"."people"`,
		`"id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL`,
		`"name" text NOT NULL`,
		`"note" varchar(40)`,
		`CONSTRAINT "people_pkey" PRIMARY KEY ("id")`,
		`CONSTRAINT "people_name_key" UNIQUE ("name")`,
		`CONSTRAINT "people_note_fk" FOREIGN KEY ("note") REFERENCES "public"."notes" ("id") ON DELETE CASCADE`,
		`CONSTRAINT "people_name_len" CHECK (length(name) > 0)`,
	} {
		if !strings.Contains(create, want) {
			t.Errorf("the table does not say %q:\n%s", want, create)
		}
	}
	// The index is its own statement, because it is not part of the table.
	if want := `CREATE INDEX "people_note_idx" ON "public"."people" USING btree ("note" DESC)`; got[1] != want {
		t.Errorf("the index reads\n\t%s\nwant\n\t%s", got[1], want)
	}
	// And the comments come last, quoted as PostgreSQL reads them.
	if !strings.Contains(got[2], `COMMENT ON TABLE "public"."people" IS 'who they are'`) {
		t.Errorf("the table's comment reads %s", got[2])
	}
	if !strings.Contains(got[3], `COMMENT ON COLUMN "public"."people"."name" IS 'what they are called'`) {
		t.Errorf("the column's comment reads %s", got[3])
	}
}

// The order is the point: drops before the columns they hold, adds after
// them, comments last.
func TestTheOrderStatementsComeBackIn(t *testing.T) {
	was := people()
	was.Uniques = []model.UniqueConstraint{{Name: "people_note_key", Columns: []string{"note"}}}

	now := people()
	now.Columns = slices.Delete(now.Columns, 2, 3) // note goes
	now.Uniques = nil                              // and the unique on it
	now.Columns = append(now.Columns, col("email", "text", true))
	now.Columns[1].Comment = "what they are called"
	// And a constraint on the column that arrives, which cannot be made
	// until there is a column to make it on.
	now.Uniques = []model.UniqueConstraint{{Name: "people_email_key", Columns: []string{"email"}}}

	got := altered(t, was, now)
	if len(got) < 4 {
		t.Fatalf("it rendered %d statements:\n%s", len(got), strings.Join(got, "\n"))
	}
	at := func(fragment string) int {
		return slices.IndexFunc(got, func(s string) bool { return strings.Contains(s, fragment) })
	}
	dropKey, dropCol := at("DROP CONSTRAINT"), at("DROP COLUMN")
	add, addKey := at("ADD COLUMN"), at("ADD CONSTRAINT")
	comment := at("COMMENT ON COLUMN")
	for _, c := range []struct {
		what     string
		at, then int
	}{
		{"a constraint dropped before the column it holds", dropKey, dropCol},
		{"a column dropped before another is added", dropCol, add},
		{"a column added before the constraint made on it", add, addKey},
		{"everything before the comments", addKey, comment},
	} {
		if c.at < 0 || c.then < 0 {
			t.Fatalf("%s: one of them is missing from\n%s", c.what, strings.Join(got, "\n"))
		}
		if c.at > c.then {
			t.Errorf("%s: they came back as\n%s", c.what, strings.Join(got, "\n"))
		}
	}
}

// Two tables cannot say which column was renamed to which, so a column that
// went and a column that arrived render as a drop and an add. Rendering them
// as a rename would be a guess, and a wrong guess throws a column's data
// away.
func TestATableCannotGuessARename(t *testing.T) {
	now := people()
	now.Columns[2].Name = "email"

	got := altered(t, people(), now)
	if len(got) != 2 {
		t.Fatalf("it rendered %v", got)
	}
	if !strings.Contains(strings.Join(got, " "), `DROP COLUMN "note"`) {
		t.Errorf("it did not drop the old column: %v", got)
	}
	if !strings.Contains(strings.Join(got, " "), `ADD COLUMN "email"`) {
		t.Errorf("it did not add the new one: %v", got)
	}
	for _, s := range got {
		if strings.Contains(s, "RENAME") {
			t.Errorf("it guessed a rename: %s", s)
		}
	}
}

// A rename is its own statement, asked for by whoever knows one happened.
func TestARenameIsAskedForOnItsOwn(t *testing.T) {
	ref := model.NewRef(model.KindTable, "db", "public", "people")
	got := renamedSQL(t, ref, "note", "email")
	want := `ALTER TABLE "public"."people" RENAME COLUMN "note" TO "email"`
	if len(got) != 1 || got[0] != want {
		t.Errorf("it rendered\n\t%s\nwant\n\t%s", strings.Join(got, "\n\t"), want)
	}
	// A rename to the same name is no statement at all.
	if got := renamedSQL(t, ref, "note", "note"); len(got) != 0 {
		t.Errorf("renaming a column to itself rendered %v", got)
	}
	// And one with a name missing is refused rather than rendered half.
	if _, err := (dialect{}).RenameColumn(ref, "note", ""); err == nil {
		t.Error("a rename to nothing was rendered")
	}
}

func TestWhatOneColumnChangingRenders(t *testing.T) {
	for _, c := range []struct {
		what string
		to   func(*model.Column)
		want string
	}{
		{"a type", func(c *model.Column) { c.Type.Native = "text" },
			`ALTER TABLE "public"."people" ALTER COLUMN "note" TYPE text`},
		{"not null", func(c *model.Column) { c.Type.Nullable = false },
			`ALTER TABLE "public"."people" ALTER COLUMN "note" SET NOT NULL`},
		{"a default", func(c *model.Column) { c.Default, c.HasDefault = "'nobody'", true },
			`ALTER TABLE "public"."people" ALTER COLUMN "note" SET DEFAULT 'nobody'`},
		{"a comment", func(c *model.Column) { c.Comment = "what they wrote" },
			`COMMENT ON COLUMN "public"."people"."note" IS 'what they wrote'`},
	} {
		t.Run(c.what, func(t *testing.T) {
			now := people()
			c.to(&now.Columns[2])
			got := altered(t, people(), now)
			if len(got) != 1 || got[0] != c.want {
				t.Errorf("it rendered\n\t%s\nwant\n\t%s", strings.Join(got, "\n\t"), c.want)
			}
		})
	}

	// Nullable and default the other way round.
	was := people()
	was.Columns[2].Default, was.Columns[2].HasDefault = "'x'", true
	now := people()
	now.Columns[2].Type.Nullable = true
	got := altered(t, was, now)
	if len(got) != 1 || got[0] != `ALTER TABLE "public"."people" ALTER COLUMN "note" DROP DEFAULT` {
		t.Errorf("dropping a default rendered %v", got)
	}
}

// A table that says the same thing renders nothing, so a designer with no
// changes has nothing to show and nothing to run.
func TestATableThatDidNotChangeRendersNothing(t *testing.T) {
	got, err := dialect{}.AlterObject(peopleRef, people(), people())
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != 0 {
		t.Errorf("it rendered %d statements: %+v", len(got), got)
	}
}

func TestRenamingTheTableComesFirstAndEverythingFollowsIt(t *testing.T) {
	now := people()
	now.Name = "humans"
	now.Columns[2].Type.Native = "text"

	got := altered(t, people(), now)
	if len(got) != 2 {
		t.Fatalf("it rendered %v", got)
	}
	if got[0] != `ALTER TABLE "public"."people" RENAME TO "humans"` {
		t.Errorf("the rename reads %s", got[0])
	}
	// What follows names the table by what it is now called, because by then
	// that is what it is called.
	if !strings.HasPrefix(got[1], `ALTER TABLE "public"."humans" `) {
		t.Errorf("what followed the rename reads %s", got[1])
	}
}

func TestAKeyChangedIsDroppedAndAdded(t *testing.T) {
	now := people()
	now.PrimaryKey = &model.PrimaryKey{Name: "people_pkey", Columns: []string{"id", "name"}}

	got := altered(t, people(), now)
	if len(got) != 2 {
		t.Fatalf("it rendered %v", got)
	}
	if got[0] != `ALTER TABLE "public"."people" DROP CONSTRAINT "people_pkey"` {
		t.Errorf("the drop reads %s", got[0])
	}
	if got[1] != `ALTER TABLE "public"."people" ADD CONSTRAINT "people_pkey" PRIMARY KEY ("id", "name")` {
		t.Errorf("the add reads %s", got[1])
	}
}

// A key nobody named is dropped by the name PostgreSQL gave it, because that
// is the only name a statement can use.
func TestAKeyNobodyNamedIsDroppedByTheNameTheEngineGaveIt(t *testing.T) {
	was := people()
	was.PrimaryKey = &model.PrimaryKey{Columns: []string{"id"}}
	now := people()
	now.PrimaryKey = nil

	got := altered(t, was, now)
	if len(got) != 1 || got[0] != `ALTER TABLE "public"."people" DROP CONSTRAINT "people_pkey"` {
		t.Errorf("it rendered %v", got)
	}
}

func TestAnIndexRendered(t *testing.T) {
	now := people()
	now.Indexes = []model.Index{{
		Name: "people_lower", Unique: true, Method: "btree",
		Columns:   []model.IndexColumn{{Expression: "lower(name)"}, {Name: "note", Descending: true}},
		Include:   []string{"id"},
		Predicate: "note IS NOT NULL",
	}}
	got := altered(t, people(), now)
	want := `CREATE UNIQUE INDEX "people_lower" ON "public"."people" USING btree (lower(name), "note" DESC) ` +
		`INCLUDE ("id") WHERE note IS NOT NULL`
	if len(got) != 1 || got[0] != want {
		t.Errorf("it rendered\n\t%s\nwant\n\t%s", strings.Join(got, "\n\t"), want)
	}
}

// A name with a quote in it is quoted, and a comment with an apostrophe is
// doubled: both are places a person's words reach a statement.
func TestNamesAndWordsAreQuoted(t *testing.T) {
	ref := model.NewRef(model.KindTable, "db", "public", "people")
	got := renamedSQL(t, ref, "note", `od"d`)
	if len(got) != 1 || !strings.Contains(got[0], `RENAME COLUMN "note" TO "od""d"`) {
		t.Errorf("the rename reads %v", got)
	}

	now := people()
	now.Columns[2].Comment = "it's theirs"
	comment := altered(t, people(), now)
	if len(comment) != 1 || !strings.Contains(comment[0], `IS 'it''s theirs'`) {
		t.Errorf("the comment reads %v", comment)
	}
}

func TestDroppingAnObject(t *testing.T) {
	ref := model.NewRef(model.KindTable, "db", "public", "people")
	got := droppedSQL(t, ref, false)
	if len(got) != 1 || got[0] != `DROP TABLE "public"."people"` {
		t.Errorf("it rendered %v", got)
	}
	got = droppedSQL(t, ref, true)
	if got[0] != `DROP TABLE "public"."people" CASCADE` {
		t.Errorf("cascading rendered %v", got)
	}
	view := model.NewRef(model.KindView, "db", "public", "recent")
	if got := droppedSQL(t, view, false); got[0] != `DROP VIEW "public"."recent"` {
		t.Errorf("a view rendered %v", got)
	}
}

// This driver says it can render DDL, and the interface is what says so.
func TestThisDialectIsADDLGenerator(t *testing.T) {
	var _ source.DDLGenerator = dialect{}
	if !(&pgSource{}).Capabilities().Schema.DDL {
		t.Error("this driver renders DDL and does not say so")
	}
}

// PostgreSQL builds an index to enforce a key or a unique constraint,
// reports it among the table's indexes under the constraint's own name, and
// will not let it be dropped on its own: it goes when the constraint goes.
func TestAnIndexThatBacksAConstraintIsLeftToIt(t *testing.T) {
	was := people()
	was.Uniques = []model.UniqueConstraint{{Name: "people_name_key", Columns: []string{"name"}}}
	// As the server reports it: the constraint, and the index it built.
	was.Indexes = []model.Index{
		{Name: "people_name_key", Unique: true, Columns: []model.IndexColumn{{Name: "name"}}},
		{Name: "people_note_idx", Columns: []model.IndexColumn{{Name: "note"}}},
	}

	now := people()
	now.Indexes = []model.Index{{Name: "people_note_idx", Columns: []model.IndexColumn{{Name: "note"}}}}

	got := altered(t, was, now)
	joined := strings.Join(got, "\n")
	if !strings.Contains(joined, `DROP CONSTRAINT "people_name_key"`) {
		t.Errorf("the constraint was not dropped:\n%s", joined)
	}
	if strings.Contains(joined, `DROP INDEX "public"."people_name_key"`) {
		t.Errorf("the index behind it was dropped on its own:\n%s", joined)
	}
	// The ordinary index is left alone, because it did not change.
	if strings.Contains(joined, "people_note_idx") {
		t.Errorf("an index nobody changed was touched:\n%s", joined)
	}
}

// Objects whose structure is their source (FR-6.5).

func viewRef(name string) model.ObjectRef {
	return model.NewRef(model.KindView, "db", "public", name)
}

func TestAViewIsReplacedInPlace(t *testing.T) {
	got := createdObj(t, viewRef("recent"),
		&model.View{Name: "recent", Definition: " SELECT * FROM people WHERE id > 40;\n"})
	want := "CREATE OR REPLACE VIEW \"public\".\"recent\" AS\nSELECT * FROM people WHERE id > 40"
	if len(got) != 1 || got[0] != want {
		t.Errorf("it rendered\n\t%s\nwant\n\t%s", strings.Join(got, "\n\t"), want)
	}
}

// A materialized view cannot be replaced in place, so it goes and is made
// again — a real difference, rendered rather than hidden.
func TestAMaterializedViewIsMadeAgain(t *testing.T) {
	ref := model.NewRef(model.KindMaterializedView, "db", "public", "totals")
	got := createdObj(t, ref,
		&model.View{Name: "totals", Materialized: true, Definition: "SELECT count(*) FROM people"})
	if len(got) != 2 {
		t.Fatalf("it rendered %v", got)
	}
	if got[0] != `DROP MATERIALIZED VIEW IF EXISTS "public"."totals"` {
		t.Errorf("the drop reads %s", got[0])
	}
	if !strings.HasPrefix(got[1], `CREATE MATERIALIZED VIEW "public"."totals" AS`) {
		t.Errorf("the create reads %s", got[1])
	}
}

// A routine is re-sent as the statement PostgreSQL printed, which already
// says CREATE OR REPLACE.
func TestARoutineIsSentBackAsItCame(t *testing.T) {
	def := "CREATE OR REPLACE FUNCTION public.f(a integer)\n RETURNS integer\n LANGUAGE sql\nAS $function$ SELECT a $function$"
	got := createdObj(t, model.NewRef(model.KindRoutine, "db", "public", "f(integer)"),
		&model.Routine{Name: "f(integer)", Definition: def + ";\n"})
	if len(got) != 1 || got[0] != def {
		t.Errorf("it rendered\n\t%s\nwant\n\t%s", strings.Join(got, "\n\t"), def)
	}
}

// A trigger is dropped and made again, because PostgreSQL had no CREATE OR
// REPLACE TRIGGER until 14 and this does not ask which version it is
// talking to.
func TestATriggerIsDroppedAndMadeAgain(t *testing.T) {
	ref := model.NewRef(model.KindTrigger, "db", "public", "people", "audit")
	def := "CREATE TRIGGER audit AFTER INSERT ON public.people FOR EACH ROW EXECUTE FUNCTION log()"
	got := createdObj(t, ref, &model.Trigger{Name: "audit", Definition: def})
	if len(got) != 2 {
		t.Fatalf("it rendered %v", got)
	}
	if got[0] != `DROP TRIGGER IF EXISTS "audit" ON "public"."people"` {
		t.Errorf("the drop reads %s", got[0])
	}
	if got[1] != def {
		t.Errorf("the create reads %s", got[1])
	}
}

func TestASequenceIsItsNumbers(t *testing.T) {
	min, max := int64(1), int64(9000)
	ref := model.NewRef(model.KindSequence, "db", "public", "people_id_seq")
	got := createdObj(t, ref, &model.Sequence{
		Name: "people_id_seq", Start: 5, Increment: 2,
		MinValue: &min, MaxValue: &max, Cycle: true, Comment: "counts people"})
	if len(got) != 2 {
		t.Fatalf("it rendered %v", got)
	}
	want := `ALTER SEQUENCE "public"."people_id_seq" INCREMENT BY 2 MINVALUE 1 MAXVALUE 9000 START WITH 5 CYCLE`
	if got[0] != want {
		t.Errorf("it rendered\n\t%s\nwant\n\t%s", got[0], want)
	}
	if got[1] != `COMMENT ON SEQUENCE "public"."people_id_seq" IS 'counts people'` {
		t.Errorf("the comment reads %s", got[1])
	}

	// No bounds means saying so, not leaving the old ones in place.
	plain := createdObj(t, ref, &model.Sequence{Name: "s", Start: 1, Increment: 1})
	if !strings.Contains(plain[0], "NO MINVALUE") || !strings.Contains(plain[0], "NO CYCLE") {
		t.Errorf("it rendered %s", plain[0])
	}
}

func TestSourceThatIsNotThereIsRefused(t *testing.T) {
	for _, c := range []struct {
		what string
		obj  any
		ref  model.ObjectRef
	}{
		{"a view with no definition", &model.View{Name: "v"}, viewRef("v")},
		{"a routine with no definition", &model.Routine{Name: "f()"},
			model.NewRef(model.KindRoutine, "db", "public", "f()")},
		{"a trigger with no definition", &model.Trigger{Name: "t"},
			model.NewRef(model.KindTrigger, "db", "public", "people", "t")},
		{"a trigger on no table", &model.Trigger{Name: "t", Definition: "CREATE TRIGGER t"},
			model.NewRef(model.KindTrigger, "db", "public")},
	} {
		t.Run(c.what, func(t *testing.T) {
			if _, err := (dialect{}).CreateObject(c.ref, c.obj); err == nil {
				t.Error("it was rendered")
			}
		})
	}
}
