//go:build conformance

package firebird

import (
	"context"
	"errors"
	"os"
	"strconv"
	"testing"
	"time"

	"github.com/ikigai-db/ikigai-db/internal/model"
	"github.com/ikigai-db/ikigai-db/internal/source"
	"github.com/ikigai-db/ikigai-db/internal/source/conformance"
)

// The live suite, against a Firebird server (T4.2).
//
//	docker run -d --name ikigai-firebird -p 53050:3050 \
//	  -e FIREBIRD_ROOT_PASSWORD=ikigai -e FIREBIRD_DATABASE=ikigai.fdb \
//	  -e FIREBIRD_USER=ikigai -e FIREBIRD_PASSWORD=ikigai \
//	  firebirdsql/firebird:5
//
// And a second one that refuses to encrypt the wire, which is how the default
// being encrypted is proved to be more than a setting:
//
//	docker run -d --name ikigai-firebird-plain -p 53051:3050 \
//	  ... -e FIREBIRD_CONF_WireCrypt=Disabled firebirdsql/firebird:5
//
// IKIGAI_REQUIRE_FIREBIRD=1 turns a skip into a failure, which is what CI
// sets; the ports and the database path are overridable for a server
// somewhere else.

const dbPath = "/var/lib/firebird/data/ikigai.fdb"

func required() bool { return os.Getenv("IKIGAI_REQUIRE_FIREBIRD") != "" }

func port(env string, dflt int) int {
	if v := os.Getenv(env); v != "" {
		if n, err := strconv.Atoi(v); err == nil {
			return n
		}
	}
	return dflt
}

func config(g source.Guard) source.ConnectionConfig {
	path := os.Getenv("IKIGAI_FIREBIRD_PATH")
	if path == "" {
		path = dbPath
	}
	return source.ConnectionConfig{
		DriverID: driverID,
		Host:     "127.0.0.1", Port: port("IKIGAI_FIREBIRD_PORT", 53050),
		Database: path, User: "ikigai",
		Secret: func(string) (string, error) { return "ikigai", nil },
		Guard:  g,
	}
}

func skipOrFail(t *testing.T, err error) {
	t.Helper()
	if required() {
		t.Fatalf("Firebird required but unavailable: %v", err)
	}
	t.Skipf("no Firebird at 127.0.0.1:%d: %v", port("IKIGAI_FIREBIRD_PORT", 53050), err)
}

// dial connects as the application would.
func dial(t *testing.T, g source.Guard) source.Source {
	t.Helper()
	var d Driver
	src, err := d.Open(context.Background(), config(g))
	if err != nil {
		skipOrFail(t, err)
	}
	t.Cleanup(func() { src.Close() })
	return src
}

// seed puts the shapes the suite reads into the database. A Firebird
// connection is to one database, so the fixture is dropped and rebuilt rather
// than made fresh: everything torn down is named here, in one list, so a
// shape added later is added in both places or not at all.
//
// Names are unquoted, so Firebird folds them to upper case and that is what
// the catalogue holds and what every reference here must use.
func seed(t *testing.T) {
	t.Helper()
	var d Driver
	src, err := d.Open(context.Background(), config(source.Guard{}))
	if err != nil {
		skipOrFail(t, err)
	}
	defer src.Close()
	fb := src.(*firebirdSource)
	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()
	// Dropping what may not be there: a fresh database has none of it, and
	// that is not a failure. Order matters — a table referred to by a foreign
	// key cannot go before the key does.
	for _, stmt := range []string{
		`DROP VIEW ADULTS`, `DROP TABLE ORDERS`, `DROP TABLE CONFORM`,
		`DROP TABLE WRITES`, `DROP TABLE TAGS`, `DROP TABLE PEOPLE`,
	} {
		fb.db.ExecContext(ctx, stmt)
	}
	for _, stmt := range []string{
		`CREATE TABLE PEOPLE (ID INTEGER NOT NULL PRIMARY KEY, NAME VARCHAR(50) NOT NULL,
			SCORE DOUBLE PRECISION, BORN DATE, META VARCHAR(200), PIC BLOB SUB_TYPE 0,
			AMOUNT NUMERIC(12,2), WHEN_ TIMESTAMP, FLAG BOOLEAN, NOTE BLOB SUB_TYPE TEXT)`,
		`CREATE TABLE TAGS (K VARCHAR(20) NOT NULL PRIMARY KEY, V VARCHAR(20))`,
		`CREATE TABLE WRITES (ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			NAME VARCHAR(50) DEFAULT 'none' NOT NULL, N INTEGER)`,
		// The conformance suite's writable table, which asks for an id the
		// server numbers from 1 when it is not given — an identity, here.
		//
		// A table of its own, with its columns quoted so that they are
		// called what the suite calls them: an unquoted name folds to upper
		// case here, and a suite asking about "id" would be asking about a
		// column no ordinary Firebird table has. WRITES above keeps the
		// names Firebird would have given it, so the driver's own tests are
		// about the spelling its users will have.
		`CREATE TABLE CONFORM (
			"id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			"name" VARCHAR(50) DEFAULT 'none' NOT NULL,
			"n" INTEGER)`,
		`CREATE VIEW ADULTS AS SELECT ID, NAME FROM PEOPLE WHERE ID > 10`,
		`CREATE TABLE ORDERS (ID INTEGER NOT NULL PRIMARY KEY, PERSON_ID INTEGER, TOTAL NUMERIC(12,2),
			CONSTRAINT ORDERS_PERSON FOREIGN KEY (PERSON_ID) REFERENCES PEOPLE(ID)
				ON DELETE CASCADE ON UPDATE CASCADE,
			CONSTRAINT ORDERS_UQ UNIQUE (PERSON_ID, TOTAL),
			CONSTRAINT ORDERS_POSITIVE CHECK (TOTAL >= 0))`,
		`CREATE DESCENDING INDEX ORDERS_TOTAL ON ORDERS (TOTAL)`,
		`COMMENT ON TABLE PEOPLE IS 'the people'`,
		`COMMENT ON COLUMN PEOPLE.NAME IS 'what they are called'`,
	} {
		if _, err := fb.db.ExecContext(ctx, stmt); err != nil {
			t.Fatalf("seeding (%.50s): %v", stmt, err)
		}
	}
	for i := 1; i <= 100; i++ {
		var born any
		if i%3 == 0 {
			born = "2000-01-0" + strconv.Itoa(1+i%2)
		}
		if _, err := fb.db.ExecContext(ctx,
			`INSERT INTO PEOPLE (ID, NAME, SCORE, BORN, META) VALUES (?, ?, ?, ?, ?)`,
			i, "person "+strconv.Itoa(i), float64(i)*1.5, born,
			`{"i": `+strconv.Itoa(i)+`}`); err != nil {
			t.Fatalf("seeding people: %v", err)
		}
	}
	for _, kv := range [][2]string{{"b", "2"}, {"a", "1"}} {
		if _, err := fb.db.ExecContext(ctx, `INSERT INTO TAGS (K, V) VALUES (?, ?)`, kv[0], kv[1]); err != nil {
			t.Fatalf("seeding tags: %v", err)
		}
	}
}

func ref(kind model.ObjectKind, name string) model.ObjectRef {
	return model.NewRef(kind, "ikigai.fdb", name)
}

func TestConformance(t *testing.T) {
	seed(t)
	conformance.Run(t, conformance.Target{
		Name: "firebird",
		Open: func(_ context.Context, t *testing.T) source.Source { return dial(t, source.Guard{}) },
		OpenGuarded: func(_ context.Context, t *testing.T, g source.Guard) source.Source {
			return dial(t, g)
		},
		Browsable: ref(model.KindTable, "PEOPLE"),
		Writable:  ref(model.KindTable, "CONFORM"),
	})
}

// A value comes back as what the table declared it, not as the storage type
// the wire names: an exact decimal and a big integer are both INT64 there, and
// a text blob and a binary one are both BLOB.
func TestLiveAValueIsWhatTheTableDeclaredIt(t *testing.T) {
	seed(t)
	src := dial(t, source.Guard{})
	ctx := context.Background()
	rs, err := src.Browse(ctx, ref(model.KindTable, "PEOPLE"), source.BrowseOptions{Limit: 1})
	if err != nil {
		t.Fatal(err)
	}
	defer rs.Close()
	want := map[string]struct {
		class  model.TypeClass
		native string
	}{
		"ID":     {model.TypeInteger, "integer"},
		"NAME":   {model.TypeString, "varchar(50)"},
		"SCORE":  {model.TypeFloat, "double precision"},
		"BORN":   {model.TypeDate, "date"},
		"PIC":    {model.TypeBytes, "blob"},
		"NOTE":   {model.TypeString, "blob sub_type text"},
		"AMOUNT": {model.TypeDecimal, "numeric(12,2)"},
		"WHEN_":  {model.TypeTimestamp, "timestamp"},
		"FLAG":   {model.TypeBool, "boolean"},
	}
	for _, c := range rs.Columns() {
		w, ok := want[c.Name]
		if !ok {
			continue
		}
		if c.Type.Class != w.class {
			t.Errorf("%s reads as %v, want %v", c.Name, c.Type.Class, w.class)
		}
		if c.Type.Native != w.native {
			t.Errorf("%s calls itself %q, want %q", c.Name, c.Type.Native, w.native)
		}
		delete(want, c.Name)
	}
	if len(want) > 0 {
		t.Errorf("columns missing from the browse: %v", want)
	}
}

// Info says what answered and where it is.
func TestLiveInfoSaysWhatItIs(t *testing.T) {
	src := dial(t, source.Guard{})
	info, err := src.Info(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	if info.Product != "Firebird" {
		t.Errorf("it calls itself %q", info.Product)
	}
	if info.Version == "" {
		t.Error("it reports no version")
	}
	for _, k := range []string{"database", "owner", "on-disk format", "page size"} {
		if info.Attrs[k] == "" {
			t.Errorf("it says nothing about the %s", k)
		}
	}
}

// The structure a table reports is the structure it has: the key, the unique
// constraint, the foreign key with both its rules, the check, the descending
// index — and not the indexes that are those constraints, reported twice.
func TestLiveATableReportsItsStructureOnce(t *testing.T) {
	seed(t)
	src := dial(t, source.Guard{})
	got, err := src.Describe(context.Background(), ref(model.KindTable, "ORDERS"))
	if err != nil {
		t.Fatal(err)
	}
	tb, ok := got.(*model.Table)
	if !ok {
		t.Fatalf("it described a table as %T", got)
	}
	if tb.PrimaryKey == nil || len(tb.PrimaryKey.Columns) != 1 || tb.PrimaryKey.Columns[0] != "ID" {
		t.Errorf("its key is %+v", tb.PrimaryKey)
	}
	if len(tb.Uniques) != 1 || len(tb.Uniques[0].Columns) != 2 {
		t.Errorf("its unique constraints are %+v", tb.Uniques)
	}
	if len(tb.ForeignKeys) != 1 {
		t.Fatalf("its foreign keys are %+v", tb.ForeignKeys)
	}
	fk := tb.ForeignKeys[0]
	if fk.RefTable != "PEOPLE" || len(fk.Columns) != 1 || fk.Columns[0] != "PERSON_ID" ||
		len(fk.RefColumns) != 1 || fk.RefColumns[0] != "ID" {
		t.Errorf("its foreign key is %+v", fk)
	}
	if fk.OnDelete != model.ActionCascade || fk.OnUpdate != model.ActionCascade {
		t.Errorf("its rules are on delete %q, on update %q", fk.OnDelete, fk.OnUpdate)
	}
	if len(tb.Checks) != 1 || tb.Checks[0].Name != "ORDERS_POSITIVE" {
		t.Errorf("its checks are %+v", tb.Checks)
	}
	// One index: the one that is not a constraint. The key's, the unique
	// constraint's and the foreign key's each have one too, and describing
	// them here would be the same three facts twice.
	if len(tb.Indexes) != 1 {
		t.Fatalf("its indexes are %+v", tb.Indexes)
	}
	ix := tb.Indexes[0]
	if ix.Name != "ORDERS_TOTAL" || len(ix.Columns) != 1 || !ix.Columns[0].Descending {
		t.Errorf("its index is %+v", ix)
	}
}

// A comment somebody wrote is read back, on the table and on the column.
func TestLiveCommentsComeBack(t *testing.T) {
	seed(t)
	src := dial(t, source.Guard{})
	got, err := src.Describe(context.Background(), ref(model.KindTable, "PEOPLE"))
	if err != nil {
		t.Fatal(err)
	}
	tb := got.(*model.Table)
	if tb.Comment != "the people" {
		t.Errorf("the table's comment is %q", tb.Comment)
	}
	for _, c := range tb.Columns {
		if c.Name == "NAME" && c.Comment != "what they are called" {
			t.Errorf("the column's comment is %q", c.Comment)
		}
	}
}

// An identity column says so, and says it can be written to: the grid needs
// both to know it may leave the value out and may also supply one.
func TestLiveAnIdentityColumnSaysSo(t *testing.T) {
	seed(t)
	src := dial(t, source.Guard{})
	got, err := src.Describe(context.Background(), ref(model.KindTable, "WRITES"))
	if err != nil {
		t.Fatal(err)
	}
	for _, c := range got.(*model.Table).Columns {
		switch c.Name {
		case "ID":
			if !c.Identity || !c.AutoIncrement {
				t.Errorf("ID: identity %v, writable %v", c.Identity, c.AutoIncrement)
			}
		case "NAME":
			if !c.HasDefault || c.Default != "'none'" {
				t.Errorf("NAME's default is %q (has one: %v)", c.Default, c.HasDefault)
			}
			if c.Identity {
				t.Error("NAME is reported as an identity")
			}
		}
	}
}

// A statement let go of is let go of on the server too, not merely looked
// away from (FR-5.5, NFR-P9).
func TestLiveACancelledStatementStops(t *testing.T) {
	seed(t)
	src := dial(t, source.Guard{})
	q := src.(source.Queryer)
	ctx, cancel := context.WithTimeout(context.Background(), 500*time.Millisecond)
	defer cancel()
	start := time.Now()
	// A cross join of a hundred rows four ways is a hundred million, which no
	// server counts in half a second.
	//
	// Firebird opens the cursor at once and does the work on the first fetch,
	// so the statement is not waited for until a row is asked for — which is
	// also how the grid reads one, and is where a cancellation has to land.
	res, err := q.Query(ctx, source.Statement{
		SQL: `SELECT COUNT(*) FROM PEOPLE a, PEOPLE b, PEOPLE c, PEOPLE d`})
	if err != nil {
		t.Fatalf("opening it: %v", err)
	}
	defer res.Rows.Close()
	_, err = res.Rows.Next(ctx)
	if !errors.Is(err, context.DeadlineExceeded) {
		t.Fatalf("reading it said %v", err)
	}
	if took := time.Since(start); took > 5*time.Second {
		t.Errorf("it took %v to give up, so the cancellation did not reach the server", took)
	}
}

// Encryption is on by default and is not a setting that quietly gives up: a
// server that will not encrypt is refused, and only an explicit choice of
// Disable connects to it (NFR-S3).
func TestLiveAServerThatWillNotEncryptIsRefused(t *testing.T) {
	path := os.Getenv("IKIGAI_FIREBIRD_PLAIN_PATH")
	if path == "" {
		path = "/var/lib/firebird/data/plain.fdb"
	}
	cfg := config(source.Guard{})
	cfg.Port = port("IKIGAI_FIREBIRD_PLAIN_PORT", 53051)
	cfg.Database = path
	var d Driver

	src, err := d.Open(context.Background(), cfg)
	if err == nil {
		src.Close()
		if required() {
			t.Fatalf("the plaintext-only server at port %d accepted an encrypted connection", cfg.Port)
		}
		t.Skip("whatever is on that port encrypts, so it is not the plaintext server")
	}
	var ce *source.ConnectError
	if !errors.As(err, &ce) {
		t.Fatalf("it said %v", err)
	}
	if ce.Kind != source.ConnectTLS {
		if !required() {
			t.Skipf("nothing is answering as a plaintext Firebird: %v", err)
		}
		t.Fatalf("it called that %v: %v", ce.Kind, err)
	}

	// And with the choice made, it connects — which is what makes the refusal
	// a default rather than a prohibition.
	cfg.TLS = source.TLSConfig{Mode: "disable"}
	plain, err := d.Open(context.Background(), cfg)
	if err != nil {
		t.Fatalf("with encryption turned off it still refused: %v", err)
	}
	plain.Close()
}
